version: "3.8"

services:
  react-app:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - middleware

  middleware:
    build: ./middleware
    ports:
      - "4000:4000"

  worker:
    build: ./worker
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - react-app
      - middleware

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
